const authEvents = require('./auth/events.js')
const beerEvents = require('./beers/events.js')

$(() => {
  $('.change-password-header').hide()
  $('#change-password-form').hide()
  $('#pullUpChangePassButton').hide()
  $('.changePassCard').hide()
  $('#sign-out-button').hide()
  $('#create-beer').hide()
  $('#show-beer').hide()
  $('#index-beers').hide()
  $('#beers-display').hide()
  $('.createBeerCard').hide()
  $('.addNewBeer').hide()
  $('#new-beer-error-message').hide()
  $('#index-error-message').hide()
  $('#sign-up-form').on('submit', authEvents.onSignUp)
  $('#sign-in-form').on('submit', authEvents.onSignIn)
  $('#change-password-form').on('submit', authEvents.onChangePassword)
  $('#sign-out-button').on('click', authEvents.onSignOut)
  $('#index-beers').on('click', beerEvents.onIndexBeers)
  $('#pullUpChangePassButton').on('click', authEvents.onPullUpChangeForm)
  $('.addNewBeer').on('click', beerEvents.onPullUpForm)
  $('#show-beer').on('submit', beerEvents.onShowBeer)
  $('#delete-beer').on('submit', beerEvents.onDeleteBeer)
  $('#update-beer').on('submit', beerEvents.onUpdateBeer)
  $('#create-beer').on('submit', beerEvents.onCreateBeer)
  $('#beers-display').on('click', '.delete-beer-list', beerEvents.onDeleteListBeer)
  $('#beers-display').on('submit', '.update-beer-list', beerEvents.onUpdateListBeer)
  $('#beers-display').on('click', '.update-current-beer', beerEvents.onUpdateCurrentBeerCard)
})
